---
title: "Analyzing The Leading Causes of Death in the USA"
author: "GWU Intro to Data Science -- DATS 6101"
output:
  html_document:
    code_folding: show
    number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
date: "2025-03-19"
---

```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes a lot of the helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
library(ezids)
```



```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(warning = F, results = "markup", message = F)
# knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times

```



# Abstract

* Briefly introduce the project and research goals.
* Summarize key findings from the EDA process.
* State the main conclusions and their relevance.
* Keep this concise and engaging for a non-technical reader.

# Intoduction


# Data Understanding & Curation


# Exploratory Data Analysis

# Statistical Testing & Technical Analysis


# Discussion & Insights


# References